### PR TITLE
Remove useless e2e test

### PR DESCRIPTION
**Pull request by RolandMa1986**
Signed-off-by: Roland.Ma <rolandma@yunify.com>

**What type of PR is this?**
 /kind failing-test

**What this PR does / why we need it**:

Remove useless e2e test, which caused the e2e action failing.

### CODE REVIEW

**Comment by yuswift** [comment]
why do we just remove the code instead of adding rbac rules for the code?  The e2e test error messages are here
```--- FAIL: TestDelayingDeliverer (0.32s)
    help_test.go:38: 
        	Error Trace:	help_test.go:38
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"pods is forbidden: User \"tester\" cannot list resource \"pods\" in API group \"\" at the cluster scope", Reason:"Forbidden", Details:(*v1.StatusDetails)(0xc000d043c0), Code:403}}
        	Test:       	TestDelayingDeliverer
FAIL
FAIL	kubesphere.io/kubesphere/test/e2e	44.226s
FAIL
Error: Process completed with exit code 1.```

**Comment by RolandMa1986** [comment]
> why do we just remove the code instead of adding rbac rules for the code? The e2e test error messages are here

It's not part of the e2e test, it was checked in by mistake.

**Pull request merged**
