### PR TITLE
Adjust metrics query for monitoring components upgrade

### PR DESCRIPTION
**Pull request by junotx**
### What this PR does / why we need it:
This pr is  to fit monitoring query in ks-apiserver for upgraded monitoring components, because of that, after https://github.com/kubesphere/ks-installer/pull/1881 upgrades the prometheus stack,  there are some metrics changes for upstream components which can refer to https://github.com/kubesphere/ks-installer/issues/1883#issuecomment-1011992004 and https://github.com/kubesphere/ks-prometheus/pull/1.

### Which issue(s) this PR fixes:

Part of https://github.com/kubesphere/ks-installer/issues/1883

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Adjust metrics query for monitoring components upgrade (https://github.com/kubesphere/ks-installer/pull/1881)
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by benjaminhuo** [comment]
Fit monitoring query for upgraded monitoring components. (The upgrades refer to https://github.com/kubesphere/ks-installer/pull/1881)
=>
Adjust metrics query for monitoring components upgrade ( https://github.com/kubesphere/ks-installer/pull/188 )

**Comment by junotx** [comment]
> Fit monitoring query for upgraded monitoring components. (The upgrades refer to [kubesphere/ks-installer#1881](https://github.com/kubesphere/ks-installer/pull/1881)) => Adjust metrics query for monitoring components upgrade ( [kubesphere/ks-installer#188](https://github.com/kubesphere/ks-installer/pull/188) )

@benjaminhuo please see the first comment for updates to this note

**Pull request merged**
