### PR TITLE
Upgrade prometheus dependencies

### PR DESCRIPTION
**Pull request by zackzhangkai**
Signed-off-by: zackzhangkai <zackzhang@yunify.com>

**What type of PR is this?**
Upgrade github.com/prometheus/client_golang to v1.5.1
Upgrade github.com/prometheus/prometheus to v1.8.2-0.20200507164740-ecee9c8abfd1

/area microservice

**Which issue(s) this PR fixes**:

https://github.com/kubesphere/kubesphere/issues/3096

https://github.com/kubesphere/kiali/pull/5

Fixes #

**Special notes for reviewers**:

/assign @zryfish 
/cc @benjaminhuo @huanggze @junotx 

**Additional documentation, usage docs, etc.**:

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@zackzhangkai Just wondering why using your private fork github.com/zackzhangkai/kiali  instead of github.com/kubesphere/kiali ？

**Comment by zackzhangkai** [comment]
> @zackzhangkai Just wondering why using your private fork github.com/zackzhangkai/kiali instead of github.com/kubesphere/kiali ？

@benjaminhuo  because this [pr](https://github.com/kubesphere/kiali/pull/5) should be merged first

**Comment by benjaminhuo** [comment]
Then you'll replace your private fork github.com/zackzhangkai/kiali with github.com/kubesphere/kiali in a new PR? @zackzhangkai

**Comment by zackzhangkai** [comment]
> Then you'll replace your private fork github.com/zackzhangkai/kiali with github.com/kubesphere/kiali in a new PR? @zackzhangkai

@benjaminhuo I have replaced it in this pr already.

**Comment by zackzhangkai** [comment]
@zryfish @benjaminhuo @junotx please reivew this pr .If there is no problem, please merge it. Thanks.

**Review by junotx — APPROVED** [review]

**Review by benjaminhuo — APPROVED** [review]
/lgtm

**Review by benjaminhuo — APPROVED** [review]
/lgtm

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@zackzhangkai I think this PR's title could be changed to `Update prometheus dependencies` because it's not client dependencies anymore.

**Comment by benjaminhuo** [comment]
@junotx You need to `git commit -s ...`

```
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
```

**Pull request merged**
