### PR TITLE
remove http1.1 support code

### PR DESCRIPTION
**Pull request by yuswift**
Signed-off-by: yuswift <yuswiftli@yunify.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
We've updated the dependencies and don't need to copy the `supportsHTTP11()` function  from `https://github.com/kubernetes/apimachinery/blob/master/pkg/util/proxy/dial.go` manaully.

### CODE REVIEW

**Comment by zryfish** [comment]
Can we also remove same code in https://github.com/kubesphere/kubesphere/blob/master/pkg/apiserver/filters/kubeapiserver.go#L76

**Comment by yuswift** [comment]
> Can we also remove same code in https://github.com/kubesphere/kubesphere/blob/master/pkg/apiserver/filters/kubeapiserver.go#L76

Done.

**Pull request merged**
