### PR TITLE
Upgrade k8s package version

### PR DESCRIPTION
**Pull request by RolandMa1986**
### What type of PR is this?
/kind feature

### What this PR does / why we need it:
This PR upgrade KubeSphere's dependencies to the latest stable version. The primary changes include:
Upgrade Kubernetes package version to 1.21.2
Upgrade Controller-runtime package  to 0.9.3
Upgrade Kubefed package  to v0.8.1
Upgrade Helm package to v3.5.0

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
Go version was upgraded to 1.16.x, the related environment needed to be upgraded too.
```

### Does this PR introduced a user-facing change?
```release-note
NONE
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wansir** [comment]
```
./hack/lint-dependencies.sh
...
Use the given commands to remove pinned module versions that aren't actually used:
GO111MODULE=on go mod edit -dropreplace github.com/stoewer/go-strcase
```

**Comment by wansir** [comment]
This commit is unnecessary https://github.com/kubesphere/kubesphere/pull/4141/commits/7772deea3436b9be85079245a17c90d4c272a881. Please rebase to https://github.com/kubesphere/kubesphere/commit/a923715062b82f12b489d43810400ff43c93dca4.

**Comment by RolandMa1986** [comment]
> This commit is unnecessary [7772dee](https://github.com/kubesphere/kubesphere/commit/7772deea3436b9be85079245a17c90d4c272a881). Please rebase to [a923715](https://github.com/kubesphere/kubesphere/commit/a923715062b82f12b489d43810400ff43c93dca4).

fixed

**Comment by zryfish** [comment]
This is a huge change, need to test ASAP. @RolandMa1986 

/approve

**Pull request merged**
