### PR TITLE
update package s2ioperator

### PR DESCRIPTION
**Pull request by soulseen**
Signed-off-by: soulseen <sunzhu@yunify.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind documentation
> /kind feature

**What this PR does / why we need it**:
update package s2ioperator

### CODE REVIEW

**Comment by zryfish** [comment]
If there is any dependency on `github.com/kubesphere/s2ioperator v0.0.12` ?  Such as wait for other PRs to merge first?

**Comment by runzexia** [comment]
@zryfish 
Other PRs do not depend on this PR, so there is no conflict. This PR can be merged first.

**Pull request merged**
