### PR TITLE
fix: fix the gateway variable name.

### PR DESCRIPTION
**Pull request by 2hangchen**
Signed-off-by: Pilipalaca <85749695@qq.com>

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
fix variable name `Conroller` to `Controller`

### CODE REVIEW

**Comment by zryfish** [comment]
@2hangchen The unit test failed, please take a look.

**Comment by wansir** [comment]
```
useradd: UID 0 is not unique
...Begin to run go vet against code.
go vet ./pkg/... ./cmd/...
# kubesphere.io/api/gateway/v1alpha1
vendor/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go:144:4: in.Conroller undefined (type *GatewaySpec has no field or method Conroller)
vendor/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go:144:3[2](https://prow.kubesphere.io/view/s3/prow-logs/pr-logs/pull/kubesphere_kubesphere/4815/pull-kubesphere-unit-test/1517145357941739520#1:build-log.txt%3A2): out.Conroller undefined (type *GatewaySpec has no field or method Conroller)
make: *** [Makefile:8[6](https://prow.kubesphere.io/view/s3/prow-logs/pr-logs/pull/kubesphere_kubesphere/4815/pull-kubesphere-unit-test/1517145357941739520#1:build-log.txt%3A6): vet] Error 2
``` 
Unit test failed caused by go vet check error, you can regenerate the deepcopy objects by the following command: 

```
make deepcopy
```

**Comment by 2hangchen** [comment]
> ```
> useradd: UID 0 is not unique
> ...Begin to run go vet against code.
> go vet ./pkg/... ./cmd/...
> # kubesphere.io/api/gateway/v1alpha1
> vendor/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go:144:4: in.Conroller undefined (type *GatewaySpec has no field or method Conroller)
> vendor/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go:144:3[2](https://prow.kubesphere.io/view/s3/prow-logs/pr-logs/pull/kubesphere_kubesphere/4815/pull-kubesphere-unit-test/1517145357941739520#1:build-log.txt%3A2): out.Conroller undefined (type *GatewaySpec has no field or method Conroller)
> make: *** [Makefile:8[6](https://prow.kubesphere.io/view/s3/prow-logs/pr-logs/pull/kubesphere_kubesphere/4815/pull-kubesphere-unit-test/1517145357941739520#1:build-log.txt%3A6): vet] Error 2
> ```
> 
> @2hangchen Unit test failed caused by go vet check error, you can regenerate the deepcopy objects by the following command:
> 
> ```
> make deepcopy
> ```

I also submitted pr in the API project, does this need to be merged?
[https://github.com/kubesphere/api/pull/1](url)

**Comment by 2hangchen** [comment]
I also submitted pr in the API project, does this need to be merged?
[https://github.com/kubesphere/api/pull/1](url)

**Comment by wansir** [comment]
`hack/update-vendor.sh` will create a symbolic link from `staging/src/kubesphere.io/api` to `vendor/kubesphere.io/api`, and it is automatically synchronized to `[https://github.com/kubesphere/api](https://github.com/kubesphere/kubesphere/pull/url)`, refer https://github.com/kubesphere/kubesphere/pull/3831.

`make deepcopy` and go ahead.

**Comment by 2hangchen** [comment]
> `hack/update-vendor.sh` will create a symbolic link from `staging/src/kubesphere.io/api` to `vendor/kubesphere.io/api`, and it is automatically synchronized to `[https://github.com/kubesphere/api](https://github.com/kubesphere/kubesphere/pull/url)`, refer #3831.
> 
> `make deepcopy` and go ahead.

👌

**Comment by wansir** [comment]
@2hangchen I found that `gateway:v1alpha1` is missing in [Makefile#L9](https://github.com/kubesphere/kubesphere/blob/master/Makefile#L9), so the `vendor/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go` will not be automatically generated. Maybe you can help us to fix the missing configuration, thanks for your time.

**Comment by 2hangchen** [comment]
> @2hangchen I found that `gateway:v1alpha1` is missing in [Makefile#L9](https://github.com/kubesphere/kubesphere/blob/master/Makefile#L9), so the `vendor/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go` will not be automatically generated. Maybe you can help us to fix the missing configuration, thanks for your time.

Ok, I'll try to do that.

**Pull request merged**
