### PR TITLE
Fix: parse openpitrix resources, so that these resources will be included in billing.

### LINKED ISSUE #3870: openpitrix resources are not included in billing.
**Describe the Bug**
Install an app with openpitrix, but resources are not include in billing.

**Versions Used**
KubeSphere: 3.1.0

**How To Reproduce**
1.  Install an app in  namespace  `test-metering` 
2. Click the `View Consumption`
3. Click the namespace ` test-metering`

**Expected behavior**
openpitrix resources are included in billing.

area/metering
kind/bug
priority/low

### PR DESCRIPTION
**Pull request by xyz-li**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Resolve openpitrix resources, so that these resources will be included in billing.
Fix typos: Change `Daemonset` to `DaemonSet` and `Statefulset` to `StatefulSet`.

**Which issue(s) this PR fixes**:

Fixes #3870

/assign @yunkunrao

### CODE REVIEW

**Comment by zryfish** [comment]
Please go through this doc https://github.com/kubesphere/community/blob/master/developer-guide/development/the-pr-author-guide-to-getting-through-code-review.md and pick a more descriptive title

**Comment by yuswift** [comment]
@xyz-li Do we need to cherry-pick this pr?

**Pull request merged**
