### PR TITLE
fix duplicate args generated when creating more than one ingress-controllers

### LINKED ISSUE #4173: duplicate args generated when creating more than one ingress-controllers
**Describe the Bug**
when creating more than two ingress-controllers, the ingress-controllers pod args are duplicate.

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: 1.19.10

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 1 masters:  8cpu/8g; all-in-one
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Create two projects: pro1 and pro2.
2. Create ingress-controller gateway for each project. And, the second ingress-controller pod args are duplicate.

     Args:
        /nginx-ingress-controller
        --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        --annotations-prefix=nginx.ingress.kubernetes.io
        --update-status
        --update-status-on-shutdown
        --configmap=$(POD_NAMESPACE)/kubesphere-router-pro1-nginx
        --watch-namespace=pro1
        --election-id=kubesphere-router-pro1
        --report-node-internal-ip-address
        --configmap=$(POD_NAMESPACE)/kubesphere-router-pro2-nginx
        --watch-namespace=pro2
        --election-id=kubesphere-router-pro2
        --report-node-internal-ip-address

**Expected behavior**
The second ingress-controller pod  should only contain its own args, excluding pro1 args.

### PR DESCRIPTION
**Pull request by styshoo**
… pod args are duplicate

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
when calling createOrUpdateRouterWorkload in route.go, we should use a deepcopy of routerOperator.routerTemplates.

### Which issue(s) this PR fixes:

Fixes #4173

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by RolandMa1986** [comment]
/lgtm 
@styshoo thanks for your contribution.
BTW "Does this PR introduced a user-facing change?" in the comments is needed.

**Comment by yuswift** [comment]
/retitle fix duplicate args generated when creating more than one ingress-controllers

**Comment by yuswift** [comment]
> /lgtm
> @styshoo thanks for your contribution.
> BTW "Does this PR introduced a user-facing change?" in the comments is needed.

I guess `None` is enough.
@styshoo thanks for your contribution!

**Comment by styshoo** [comment]
> > /lgtm
> > @styshoo thanks for your contribution.
> > BTW "Does this PR introduced a user-facing change?" in the comments is needed.
> 
> I guess `None` is enough.
> @styshoo thanks for your contribution!

yeah, I've edited  the comment.

**Pull request merged**
