### PR TITLE
filter out metrics with empty resource_name when sorting

### LINKED ISSUE #1464: 修改node节点的CPU和内存后，集群会临时多出一个节点
测试环境：1个master和2个node节点；
测试步骤:
1、修改其中一个node节点的内存和CPU配置后，在ks的节点监控中会临时多出一个节点，该节点名称是空白的，监控数据为空，后来才恢复正常，稍后补图

### PR DESCRIPTION
**Pull request by huanggze**
Signed-off-by: huanggze <loganhuang@yunify.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1464

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zryfish** [comment]
do rebase and push again

**Comment by huanggze** [comment]
done

**Pull request merged**
