### PR TITLE
optimize ks-core chart

### PR DESCRIPTION
**Pull request by 24sama**
### What type of PR is this?

/kind cleanup

### What this PR does / why we need it:
* Remove useless yaml file.
* Support custom initial password.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Optimize ks-core chart.
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wansir** [comment]
@24sama any updates?

**Comment by 24sama** [comment]
@wansir  please continue.

**Pull request merged**
