### PR TITLE
Fix the issues which caused by upper-case

### PR DESCRIPTION
**Pull request by LinuxSuRen**
**What type of PR is this?**
/kind bug
/area iam

**What this PR does / why we need it**:
Got issues with invalid username. It cannot be upper-case.
Error msg:
```
Invalid user name. Username can only contain lowercase letters and numbers.
```

**Which issue(s) this PR fixes**:

**Special notes for reviewers**:

**Additional documentation, usage docs, etc.**:

### CODE REVIEW

**Comment by wansir** [comment]
Just commit to the release-3.0 branch, we have added the account confirmation process in 3.1.

image

**Comment by LinuxSuRen** [comment]
> We have added the account confirmation process in 3.1.
> 

Yes, I saw it. But the back-end just returns the username with upper-case.

**Comment by wansir** [comment]
> > We have added the account confirmation process in 3.1.
> 
> Yes, I saw it. But the back-end just returns the username with upper-case.

I think it should be converted by the front-end user. If the username contains special characters, it needs to be reconfirmed. We cannot ensure that the username format of all identity providers is consistent,  should return the original username (conversion is unnecessary).

**Comment by LinuxSuRen** [comment]
> > > We have added the account confirmation process in 3.1.
> > 
> > 
> > Yes, I saw it. But the back-end just returns the username with upper-case.
> 
> I think it should be converted by the front-end user. If the username contains special characters, it needs to be reconfirmed. We cannot ensure that the username format of all identity providers is consistent, should return the original username (conversion is unnecessary).

Fair enough. I'm going to close it.

**Pull request closed without merging**
