### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Major updates

```
istio.io/api v0.0.0-20201113182140-d4b7e3fc2b44
istio.io/client-go v0.0.0-20201113183938-0734e976e785
k8s.io/api => k8s.io/api v0.18.6
k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.18.6
k8s.io/apimachinery => k8s.io/apimachinery v0.18.6
k8s.io/apiserver => k8s.io/apiserver v0.18.6
k8s.io/cli-runtime => k8s.io/cli-runtime v0.18.6
k8s.io/client-go => k8s.io/client-go v0.18.6
k8s.io/code-generator => k8s.io/code-generator v0.18.6
k8s.io/component-base => k8s.io/component-base v0.18.6
k8s.io/gengo => k8s.io/gengo v0.0.0-20200114144118-36b2048a9120
k8s.io/klog => k8s.io/klog v1.0.0
k8s.io/klog/v2 => k8s.io/klog/v2 v2.0.0
k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20200410145947-61e04a5be9a6
k8s.io/kubectl => k8s.io/kubectl v0.18.6
k8s.io/metrics => k8s.io/metrics v0.18.6
k8s.io/utils => k8s.io/utils v0.0.0-20200603063816-c1c6865ac451
sigs.k8s.io/application => sigs.k8s.io/application v0.8.4-0.20201016185654-c8e2959e57a0
sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.6.4
sigs.k8s.io/controller-tools => sigs.k8s.io/controller-tools v0.4.0
sigs.k8s.io/kind => sigs.k8s.io/kind v0.8.1
sigs.k8s.io/kubefed => sigs.k8s.io/kubefed v0.4.0
github.com/kubernetes-csi/external-snapshotter/client/v3 v3.0.0
github.com/prometheus/client_golang v1.7.1
github.com/prometheus/common v0.10.0
github.com/prometheus/prometheus v1.8.2-0.20200507164740-ecee9c8abfd1
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by min-zh — COMMENTED** [review]
/lgtm

**Comment by zackzhangkai** [comment]
Major updates:

1. use Application from https://github.com/kubernetes-sigs/application directly instead of https://github.com/kubesphere/application.

2. Generate API typed clients for application, placed in kubesphere.io/kubesphere/pkg/simple/client/app.

3. Remove old codes of kiali.

**Comment by zackzhangkai** [comment]
@wansir 
https://github.com/wansir/kubesphere/pull/4

1. refactor application (use controller-runtime)
2. use typed api for resources (controller-runtime client cannot use cache, directly request API server)

Please reset the latest commit of this PR.

**Comment by zheng1** [comment]
Can anybody come and fix the conflict in this PR?

**Comment by zackzhangkai** [comment]
https://github.com/kubesphere/kubesphere/issues/3274

**Pull request merged**
