### PR TITLE
ci: update go version to 1.18

### PR DESCRIPTION
**Pull request by zaunist**
### What this PR does / why we need it:

Recently, the Kubesphere repo has updated go version to 1.18, so CI should update too.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wansir** [comment]
@zaunist Thanks for your contribution! We'd better change the docker image of the build stage, refer to https://github.com/kubesphere/kubesphere/blob/master/build/ks-apiserver/Dockerfile#L18, https://github.com/kubesphere/kubesphere/blob/master/build/ks-controller-manager/Dockerfile#L25. The `setup-go` step in Github action is not used anymore.

**Comment by zaunist** [comment]
> @zaunist Thanks for your contribution! We'd better change the docker image of the build stage, refer to https://github.com/kubesphere/kubesphere/blob/master/build/ks-apiserver/Dockerfile#L18, https://github.com/kubesphere/kubesphere/blob/master/build/ks-controller-manager/Dockerfile#L25. The `setup-go` step in Github action is not used anymore.

Thanks for your reply, I will update this pr to change Dockerfile instead of Github Action.

**Pull request merged**
