### PR TITLE
[WIP] regenerate crd files && change folder cmd/controller-manager name to cmd/ks-controller-manage

### PR DESCRIPTION
**Pull request by yuswift**
…cmd/ks-controller-manager

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
Do some clean-up work.

### CODE REVIEW

**Comment by zryfish** [comment]
goimports formatt issue, maybe we need rule out `pkg/apis` as well when goimports formatting.

**Comment by zryfish** [comment]
need to rerun `hack/update-goimports.sh` and undo changes to `pkg/apis/*`

**Comment by yuswift** [comment]
@zryfish rebased the code and the goimports passed.

**Comment by wansir** [comment]
Failed to apply the new CRD. Maybe this issue https://github.com/kubernetes/kubernetes/issues/80493.

**Comment by yuswift** [comment]
The generated crd files can not be applied. Working on it.

**Comment by yuswift** [comment]
/retitle [WIP] regenerate crd files && change folder cmd/controller-manager name to cmd/ks-controller-manage

**Comment by zackzhangkai** [comment]
After do `make deploy`, the errors came out as 
```
"error when creating "servicemesh.kubesphere.io_strategies.yaml": CustomResourceDefinition.apiextensions.k8s.io "strategies.servicemesh.kubesphere.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string""
```

This is the controller-tools [bug](https://github.com/kubesphere/kubesphere/pull/3661). We worked around by change the type `Any` to `object` by hand.

` type: Any` -> `type: object`

**Comment by yuswift** [comment]
/close
see #3702

**Pull request closed without merging**
