### PR TITLE
Add support to proxy Jenkins API with POST method

### PR DESCRIPTION
**Pull request by LinuxSuRen**
**What type of PR is this?**
/kind feature
/area devops

**What this PR does / why we need it**:
This PR will add support to proxy Jenkins API with the `POST` method. Currently, it only supports the `GET` method.

For security reasons, Jenkins will protect the API with the `POST` method. For now,  the API for getting Gitlab servers from Jenkins requires it.

**Which issue(s) this PR fixes**:

**Special notes for reviewers**:

**Additional documentation, usage docs, etc.**:

/cc @kubesphere/sig-devops

### CODE REVIEW

**Comment by shaowenchen** [comment]
What is the purpose of adding the post proxy?

**Comment by LinuxSuRen** [comment]
> What is the purpose of adding the post proxy?

The Gitlab source branch API method is `POST`. See also https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/8eb7bb2eee959956a5545b5fecfbe0add6b293dd/src/main/java/io/jenkins/plugins/gitlabserverconfig/action/GitlabAction.java#L50

**Comment by zryfish** [comment]
@LinuxSuRen Please add description and why we need it in the PR description section

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen Please add description and why we need it in the PR description section

Done.

**Pull request merged**
