### PR TITLE
Merge pull request #1 from kubesphere/master

### PR DESCRIPTION
**Pull request by thread9killer**
update

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by thread9killer** [comment]
11

**Comment by FeynmanZhou** [comment]
As I see the updates are empty, does this PR make sense?

**Comment by zryfish** [comment]
What's the purpose of this PR, and I can't see any changes. What do you want to change?

**Comment by RolandMa1986** [comment]
I'm going to close this PR first. Please fill another PR if there are commits needs to be merged.
/close

**Pull request closed without merging**
