### PR TITLE
 support CAS identity provider

### PR DESCRIPTION
**Pull request by wansir**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Support CAS identity provider.

### CODE REVIEW

**Comment by zryfish** [comment]
Please create an issue to describe this work item first, and link this PR to that issue.

**Comment by wansir** [comment]
Related to https://github.com/kubesphere/kubesphere/issues/3047.

**Comment by RolandMa1986** [comment]
@wansir Why we need to merge this PR to release-3.0?

**Comment by wansir** [comment]
Related to https://github.com/kubesphere/kubesphere/pull/3352

/close

**Pull request closed without merging**
