### PR TITLE
[v3.2] Add grafana dashboard importing API

### LINKED ISSUE #4195: [v3.2] Import Grafana Dashboard in custom monitoring
## Background
Grafana is a successful and widely used observability tool. In the current release, we have supported importing dashboards from Grafana dashboard templates.

Refer to [here](https://github.com/kubesphere/monitoring-dashboard#converter-tool), we have finished features like below:
- a new version v1alpha2 for CRD has been provided, which supports more fields.
- the new version and the older version are compatible with each other.
- add a converter tool, aims to help for importing Grafana dashboard templates, and convert to kubesphere dashboard manifests.

In the near future, we will integrate these interfaces on the backend section.

## Plans
* [ ] Import grafana dashboard and convert it to KubeSphere dashboard

/kind design
/area monitoring
/area observability
/kind feature-request

### PR DESCRIPTION
**Pull request by zhu733756**
Signed-off-by: zhu733756 <talonzhu@yunify.com>

Import Grafana template and convert it to KubeSphere dashboard

/kind design
/area monitoring
/area observability
/kind feature-request
/area console

### Background
Grafana is a successful and widely used observability tool. In the current release, we have supported importing dashboards from Grafana dashboard templates.

Refer to [here](https://github.com/kubesphere/monitoring-dashboard#converter-tool), we have finished features like below:
- a new version v1alpha2 for CRD has been provided, which supports more fields.
- the new version and the older version are compatible with each other.
- add a converter tool, aims to help for importing Grafana dashboard templates, and convert to kubesphere dashboard manifests.

### What this PR does / why we need it:

This pr aims to integrate these interfaces on the backend section.

For a detailed API description, the API integrates with a grouped version "monitoring.kubesphere.io/v1alpha3". 
The completed request API maybe like this as follows:
```
/kapis/monitoring.kubesphere.io/v1alpha3/dashboard/template
```
We can reach the backend by post request with three parameters:
- `grafanaDashboardName`:  the name of this Grafana template needed to convert.
- `grafanaDashboardUrl`: the link to download this Grafana template. 
- `grafanaDashboardContent`: the whole JSON content needed to convert.
> Note that the parameter `grafanaDashboardName` is indispensable, and the requested parameter `grafanaDashboardUrl` and `grafanaDashboardContent` cannot be empty at the same time.

### Which issue(s) this PR fixes:

fix #4195

### Special notes for reviewers:
Currently, this API only supports create cluster scope dashboard.
A sample can be described as follow:
```
curl -d '{"grafanaDashboardName":"test2","grafanaDashboardUrl":"https://grafana.com/api/dashboards/7362/revisions/5/download"}' -H "Content-Type: application/json" localhost:9090/kapis/monitoring.kubesphere.io/v1alpha3/dashboard/template
```

### CODE REVIEW

**Review by benjaminhuo — APPROVED** [review]
/lgtm

**Comment by benjaminhuo** [comment]
The release notes need to be adjusted @zhu733756 :

`We can import Grafana templates in two ways, either through a URL or paste JS Content. Once the request is received, a Kubesphere ClusterDashboard will be produced if it does not exist before.`

=>

`Users can now import Grafana dashboards either by specifying dashboard URL or by uploading the Grafana Dashboard json file. KubeSphere will convert Grafana dashboard into KubeSphere ClusterDashboard behind the scene`

**Comment by zhu733756** [comment]
> The release notes need to be adjusted @zhu733756 :
> 
> `We can import Grafana templates in two ways, either through a URL or paste JS Content. Once the request is received, a Kubesphere ClusterDashboard will be produced if it does not exist before.`
> 
> =>
> 
> `Users can now import Grafana dashboards either by specifying the Grafana dashboard URL or by uploading the Grafana Dashboard json file. KubeSphere will convert Grafana dashboard into KubeSphere ClusterDashboard behind the scene`

fixed

**Pull request merged**
