### PR TITLE
fix dead links in readme.md

### PR DESCRIPTION
**Pull request by stoneshi-yunify**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
- fix dead links

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by FeynmanZhou — APPROVED** [review]

**Comment by zryfish** [comment]
@stoneshi-yunify  need to sign off

**Comment by stoneshi-yunify** [comment]
@zryfish I have amended and signed off the commit, not sure why the ci bot did not remove the `dco-signoff: no` label

**Comment by zryfish** [comment]
> @zryfish I have amended and signed off the commit, not sure why the ci bot did not remove the `dco-signoff: no` label

not all of your commits are signed, recommend open another PR and close this one

**Pull request closed without merging**
