### PR TITLE
Update the download version to 3.2.0

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Signed-off-by: FeynmanZhou <feynman@kubesphere.io>

### What type of PR is this?

/kind documentation

### What this PR does / why we need it:

Update the download version to 3.2.0

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
None
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None

```

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
IMO, we might don't need to put this PR into the changelog.

**Comment by FeynmanZhou** [comment]
> IMO, we might don't need to put this PR into the changelog.

Sure, minor doc updates will not be included, I removed it.

**Comment by zryfish** [comment]
@FeynmanZhou need to fill the release note section

**Pull request merged**
