### PR TITLE
fix pr_template add all labels for pr bug

### PR DESCRIPTION
**Pull request by yuswift**
Signed-off-by: yuswift <yuswift2018@gmail.com>

### What this PR does / why we need it:
Currently, If a user opens a pr for kubesphere and writes nothing in the pr comment, the robot will add all labels for the pr. IMO, it's not reasonable, cause not all of the users will notice that they should add only one label for the pr.
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zryfish** [comment]
Fair enough, I suspect it's related to our Prow, maybe we need to upgrade. Since Kubernetes is using the same PR template, but they seem ok. 

/lgtm

**Comment by yuswift** [comment]
> Fair enough, I suspect it's related to our Prow, maybe we need to upgrade. Since Kubernetes is using the same PR template, but they seem ok.
> 
> /lgtm

Alright, I will take a look at the configuration of the prow.

**Review by LinuxSuRen — APPROVED** [review]

**Comment by zryfish** [comment]
> > Fair enough, I suspect it's related to our Prow, maybe we need to upgrade. Since Kubernetes is using the same PR template, but they seem ok.
> > /lgtm
> 
> Alright, I will take a look at the configuration of the prow.

Don't bother, I'm working on a new Prow deployment, and hope to migrate our CI to Prow soon. So your PR is good enough for now.

**Comment by yuswift** [comment]
/hold
It seems that we need to upgrade the prow. ref: https://github.com/kubernetes/test-infra/pull/17261

**Comment by yuswift** [comment]
> > > Fair enough, I suspect it's related to our Prow, maybe we need to upgrade. Since Kubernetes is using the same PR template, but they seem ok.
> > > /lgtm
> > 
> > 
> > Alright, I will take a look at the configuration of the prow.
> 
> Don't bother, I'm working on a new Prow deployment, and hope to migrate our CI to Prow soon. So your PR is good enough for now.

Got it.
/unhold

**Comment by yuswift** [comment]
/close
we have upgraded the prow

**Pull request closed without merging**
