### PR TITLE
update package dependencies

### PR DESCRIPTION
**Pull request by fengshunli**
fixed the installation package with vulnerabilities
image

### CODE REVIEW

**Comment by wansir** [comment]
Please upgrade dependencies separately, and associate related issues, preferably mentioning relevant background like this https://github.com/kubesphere/kubesphere/pull/5426.

**Comment by fengshunli** [comment]
> @fengshunli Thanks for your contribution! Please upgrade dependencies separately, and associate related issues, preferably mentioning relevant background like this #5426.

added description @wansir

**Review by wansir — CHANGES_REQUESTED** [review]
It's a symlink. You can use `hack/pin-dependency.sh` to pin the version, and run `hack/update-vendor.sh` to rebuild the vendor directory.

**Comment by fengshunli** [comment]
> It's a symlink. You can use `hack/pin-dependency.sh` to pin the version, and run `hack/update-vendor.sh` to rebuild the vendor directory.

How to update the hack/tools/go.mod file

**Comment by wansir** [comment]
> hack/pin-dependency.sh

```
Usage:
  hack/pin-dependency.sh $MODULE $SHA-OR-TAG

Example:
  hack/pin-dependency.sh github.com/docker/docker 501cb131a7b7
```

**Comment by fengshunli** [comment]
> > hack/pin-dependency.sh
> 
> ```
> Usage:
>   hack/pin-dependency.sh $MODULE $SHA-OR-TAG
> 
> Example:
>   hack/pin-dependency.sh github.com/docker/docker 501cb131a7b7
> ```

I have tested it and cannot update the dependency packages under hack/tools/go.mod

**Comment by wansir** [comment]
> > > hack/pin-dependency.sh
> > 
> > 
> > ```
> > Usage:
> >   hack/pin-dependency.sh $MODULE $SHA-OR-TAG
> > 
> > Example:
> >   hack/pin-dependency.sh github.com/docker/docker 501cb131a7b7
> > ```
> 
> I have tested it and cannot update the dependency packages under hack/tools/go.mod
> 
> These dependent packages and other mods have been updated, but hack/tools/go.mod will still be displayed
> 
> image

My mistake, `hack/tools` is copied from `https://github.com/kubernetes/kubernetes/blob/master/hack/tools/tools.go`,  `hack/tools/go.mod`  needs to update manually.

**Comment by fengshunli** [comment]
> > > > hack/pin-dependency.sh
> > > 
> > > 
> > > ```
> > > Usage:
> > >   hack/pin-dependency.sh $MODULE $SHA-OR-TAG
> > > 
> > > Example:
> > >   hack/pin-dependency.sh github.com/docker/docker 501cb131a7b7
> > > ```
> > 
> > 
> > I have tested it and cannot update the dependency packages under hack/tools/go.mod
> > These dependent packages and other mods have been updated, but hack/tools/go.mod will still be displayed
> > image
> 
> My mistake, `hack/tools` is copied from `https://github.com/kubernetes/kubernetes/blob/master/hack/tools/tools.go`, `hack/tools/go.mod` needs to update manually.

I have updated everything except tools/go.mod, which can be merged

**Review by wansir — APPROVED** [review]

**Pull request merged**
