### PR TITLE
Support snapshotcontent management

### LINKED ISSUE #4282: Support volumesnapshotcontent management in ks-console
# Background
Currently ks-console only support volumesnapshot management, it does not support volumesnapshotcontent management (crud).

volumesnapshot is like pvc while volumesnapshotcontent is like pv.

# Proposal
Support volumesnapshotcontent management in console. Just like the pv management we did in ks 3.2.

/area storage
/area console
/kind feature-request

### PR DESCRIPTION
**Pull request by f10atin9**
Signed-off-by: f10atin9 <f10atin9@kubesphere.io>

### What type of PR is this?

/kind feature

### What this PR does / why we need it:
In order to support the management of snapshotcontent in ks-console
### Which issue(s) this PR fixes:

Fixes #4282 

### Special notes for reviewers:
```
None
```

### Does this PR introduced a user-facing change?

```release-note
Added a new api for snapshotcontent so that it can be displayed in the console. 
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by stoneshi-yunify — APPROVED** [review]
/lgtm

**Comment by zryfish** [comment]
@f10atin9  I think we should add release notes since there are API changes, adding a new API.

**Comment by f10atin9** [comment]
> @f10atin9 I think we should add release notes since there are API changes, adding a new API.

OK, I've added it.

**Pull request merged**
