### PR TITLE
Fix the tiny typo in ks-openapi-spec

### PR DESCRIPTION
**Pull request by sxmatch**
There is tiny typo in Create Namespace API.
So fix it quickly.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xyz-li** [comment]
The sentence is generated from this line. You only need correct the typo in it.

https://github.com/kubesphere/kubesphere/blob/d87d7d2428e424aa4fc40077133c3226a9e9b77e/pkg/kapis/tenant/v1alpha2/register.go#L193

**Comment by sxmatch** [comment]
> The sentence is generated from this line. You need correct the typo in it too.
> 
> https://github.com/kubesphere/kubesphere/blob/d87d7d2428e424aa4fc40077133c3226a9e9b77e/pkg/kapis/tenant/v1alpha2/register.go#L193

sure

**Pull request merged**
