### PR TITLE
Removed hack/install_kubebuilder.sh

### LINKED ISSUE #4187: remove `hack/install_kubebuilder.sh`
**Describe the Bug**
ref https://github.com/kubesphere/kubesphere/pull/4186

### PR DESCRIPTION
**Pull request by nathan-415**
### What type of PR is this?
/kind cleanup

### What this PR does / why we need it:

* removed hack/install_kubebuilder.sh https://github.com/kubesphere/kubesphere/issues/4187

### Which issue(s) this PR fixes:

Fixes #4187 
Ref #4189 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by yuswift** [comment]
/hold
The GitHub action failed becasue of the removed file, I guess we need to remove the `install kubebuilder` step.

**Comment by yuswift** [comment]
https://github.com/kubesphere/kubesphere/blob/eae248b3c97aa264236582314e911b5203ef4e03/.github/workflows/build.yml#L42

**Comment by yuswift** [comment]
I created a new issue. #4189

**Comment by nathan-415** [comment]
> https://github.com/kubesphere/kubesphere/blob/eae248b3c97aa264236582314e911b5203ef4e03/.github/workflows/build.yml#L42

Thank You @yuswift , I have removed that from `build.yml`.

**Comment by yuswift** [comment]
> > https://github.com/kubesphere/kubesphere/blob/eae248b3c97aa264236582314e911b5203ef4e03/.github/workflows/build.yml#L42
> 
> Thank You @yuswift , I have removed that from `build.yml`.

Thanks!

**Comment by yuswift** [comment]
Please change `Fixes #4189` to `Ref #4189`, cause we should remove the Github workflow completely instead of just remove one line, we can remove it in another pr, so this pr shouldn't fix the issue.

**Comment by yuswift** [comment]
hi @nathan-415 The ci failed because https://github.com/kubesphere/kubesphere/pull/4186 is not merged. Once it is merged, you need to rebase then the ci will pass. So you don't need to do anything now, thanks for your contribution!

**Comment by yuswift** [comment]
could you please rebase the code? Thanks!

**Comment by nathan-415** [comment]
> could you please rebase the code? Thanks!

Thanks, I have rebased it!

**Comment by yuswift** [comment]
/lgtm
@nathan-415 thanks for your contribution!
/cc @zryfish

**Comment by zryfish** [comment]
/approve

@nathan-415  Thanks for your contribution!

**Pull request merged**
