### PR TITLE
fix events search bug when no events

### LINKED ISSUE #2528: Got error when searching events
I have no event today, no es index generated. so here should be zero, but got error.

image

image

### PR DESCRIPTION
**Pull request by junotx**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2528 

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by huanggze** [comment]
double checked with logging and auditing, both are working as expected.

/lgtm

**Comment by huanggze** [comment]
I see signoff is missing @junotx

**Comment by benjaminhuo** [comment]
@junotx remember to sign the commit with git commit -s option

**Pull request merged**
