### PR TITLE
fix: migration some resource API to v1alpha3 

### LINKED ISSUE #2440: Problems with queries based on applied fields
**Describe the Bug**
Problems with queries based on applied fields
1. In the list of services, when the query is made based on the applied fields, the query results show the services whose applied fields do not match the query fields
查询结果1

2. In the workload list, when queries are made against application fields, the results of the query show the workload where the applied fields do not match the query fields
查询结果2

3. In the container group list, the query is based on the applied fields, and when there is  containers containing the set query fields,  but the query result is empty
查询结果3

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.16.12
member1-v1.18.5
member2-v1.17.8

**Environment**
host: 1node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

API resource v1alpha2 support labelSelector.

**Which issue(s) this PR fixes**:

Fixes #2440

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zryfish** [comment]
This is a massive change, we are retiring v1alpha2 APIs, why still working on these?

**Comment by wansir** [comment]
> This is a massive change, we are retiring v1alpha2 APIs, why still working on these?

The API that needs labelSelector is migrated to v1alpha3.

**Pull request merged**
