### PR TITLE
add monitoring dashboard query api

### PR DESCRIPTION
**Pull request by junotx**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

add monitoring dashboard query api to support fuzzy match

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubesphere/kubesphere/issues/3451 

/area monitoring

/cc @wansir 
/cc @benjaminhuo

### CODE REVIEW

**Review by benjaminhuo — APPROVED** [review]
/lgtm

**Comment by zryfish** [comment]
Why are there so many changes, have you run `hack/update-vendor.sh`? Also, please resolve conflicts.

**Comment by junotx** [comment]
> Why are there so many changes, have you run `hack/update-vendor.sh`? Also, please resolve conflicts.

A new dependency package was introduced so that the vendor was also updated. The conflicts will then be resolved

**Review by benjaminhuo — APPROVED** [review]
/lgtm

**Pull request merged**
