### PR TITLE
feature: add devops roadmap

### PR DESCRIPTION
**Pull request by shaowenchen**
Signed-off-by: shaowenchen <mail@chenshaowen.com>

**What type of PR is this?**

 /kind documentation

**What this PR does / why we need it**:

make the roadmap more clear

/assign @LinuxSuRen  @zryfish

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
I would suggest that adding the following items into the roadmap

* [x] Support Gitlab with Kubesphere multi-branch pipeline [#3100](https://github.com/kubesphere/kubesphere/issues/3100)

**Comment by shaowenchen** [comment]
> I would suggest that adding the following items into the roadmap
> 
> * [x]  Support Gitlab with Kubesphere multi-branch pipeline [#3100](https://github.com/kubesphere/kubesphere/issues/3100)

done

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
