### PR TITLE
add rulegroup definitions for different scopes

### PR DESCRIPTION
**Pull request by junotx**
### What type of PR is this?
/kind feature

### What this PR does / why we need it:

Define the following CRDs:

- RuleGroup: its instances take effect in its namespace
- ClusterRuleGroup: its instances take effect in its cluster
- GlobalRuleGroup: its instances take effect for all clusters

They will be used to provide easier alerting rule operations. 

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Introduce CRDs to define alerting rules with defferent scopes for easier alerting rule operations
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wansir** [comment]
/hold 

The go version used in `build-tools` has been upgraded to 1.18.4, which will cause the ci job to fail.

**Comment by benjaminhuo** [comment]
> /hold
> 
> The go version used in `build-tools` has been upgraded to 1.18.4, which will cause the ci job to fail.

reverting go version to 1.17 for build-tools will fix this? @wansir

**Pull request merged**
