### PR TITLE
Add "readyToUse" filter field for volumesnapshotcontent

### PR DESCRIPTION
**Pull request by f10atin9**
Signed-off-by: f10atin9 <f10atin9@kubesphere.io>

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
After adding this, the console can filter the volumesnapshotcontent by the ReadyToUse field.
### Which issue(s) this PR fixes:

Fixes #
#4596 
### Special notes for reviewers:
```
None
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by stoneshi-yunify — COMMENTED** [review]
/LGTM

**Comment by f10atin9** [comment]
/cc @zryfish 
Please review this fix, thanks a lot.

**Pull request merged**
