### PR TITLE
fix hyperlink format in README_zh.md

### LINKED ISSUE #4454: hyperlink format for "安装体验 KubeSphere " missing space in README_zh.md
In idea GoLang, the hyperlink for  install kubeSphere like the picture below:
image

look like missing a space for it.

### PR DESCRIPTION
**Pull request by wangyao-cmss**
### What type of PR is this?
/kind documentation

### Which issue(s) this PR fixes:

Fixes #4454

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
fix  hyperlink format for "安装体验 KubeSphere" in README_zh.md
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
Thanks for your contribution!

Hi @kubesphere/sig-docs ,

Do you think it is necessary to accept this change?

**Comment by zryfish** [comment]
The trailing period is breaking the hyperlink, I think it's necessary. 
/lgtm

**Pull request merged**
