### PR TITLE
feat: support user-facing role filter

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**

/kind feature
/kind api-change

**What this PR does / why we need it**:

 support user-facing role filter

**Which issue(s) this PR fixes**:

#1094

### CODE REVIEW

**Comment by zryfish** [comment]
what's facing

**Comment by wansir** [comment]
> what's facing

user-facing role means role created by user from kubesphere dashboard

**Comment by zryfish** [comment]
> > what's facing
> 
> user-facing role means role created by user from kubesphere dashboard

difficult to understand, choose another name

**Comment by wansir** [comment]
> > > what's facing
> > 
> > 
> > user-facing role means role created by user from kubesphere dashboard
> 
> difficult to understand, choose another name

also used in k8s docs, https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles

**Comment by zryfish** [comment]
> > > > what's facing
> > > 
> > > 
> > > user-facing role means role created by user from kubesphere dashboard
> > 
> > 
> > difficult to understand, choose another name
> 
> also used in k8s docs, https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles

OK, please add comments to it, without context, it's hard to understand

**Pull request merged**
