### PR TITLE
Fix metering chart display error when switched into network flows consumption.

### PR DESCRIPTION
**Pull request by yunkunrao**
Signed-off-by: Rao Yunkun <yunkunrao@yunify.com>

**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:

Fixes issue https://github.com/kubesphere/kubesphere/issues/3805

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
Please provide a more readable title

**Comment by yunkunrao** [comment]
> Please provide a more readable title

Got it

**Pull request merged**
