### PR TITLE
Fix the pipeline do not sync with Jenkins

### PR DESCRIPTION
**Pull request by LinuxSuRen**
**What type of PR is this?**
/kind bug
/area devops

**What this PR does / why we need it**:
Fix the issue that Pipeline cannot sync with Jenkins.

**Which issue(s) this PR fixes**:
None.

**Special notes for reviewers**:

**Additional documentation, usage docs, etc.**:

### CODE REVIEW

**Comment by zryfish** [comment]
@LinuxSuRen conflicts

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen conflicts

It's done.

**Pull request merged**
