### PR TITLE
fix `go mod tidy` error

### PR DESCRIPTION
**Pull request by yuswift**
Signed-off-by: yuswift <yuswift2018@gmail.com>

### What type of PR is this?
/kind bug

`go mod tidy` 
```
go: downloading sigs.k8s.io/application v0.8.3
verifying sigs.k8s.io/application@v0.8.3: checksum mismatch
	downloaded: h1:dL2dYfNFZIdpwLc/pLecfW5fLPtlAvBv5Vwk+4EalV0=
	go.sum:     h1:5UETobiVhxTkKn3pIESImXiMNmSg3VkM5+JvmYGDPko=
```

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?
```
None
```

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
I've tested it on GitPod. It works well.
/lgtm

**Comment by JohnNiang** [comment]
IMO, we should make some changes in CI to ensure the go module is clean and stable. Please have a look at:

https://github.com/kubesphere/ks-devops/blob/481526eff7e6e7c996cd85e1ad5720797b4bd76d/.github/workflows/lint.yaml#L19-L28

**Pull request merged**
