### PR TITLE
search image from dockerhub

### PR DESCRIPTION
**Pull request by soulseen**
Signed-off-by: soulseen <sunzhu@yunify.com>

**What type of PR is this?**
/kind documentation
/kind feature

**What this PR does / why we need it**:

search image from dockerhub

### CODE REVIEW

**Comment by runzexia** [comment]
I think there needs to be some way to determine if it is an offline environment. I think the current implementation will have some problems in the offline environment.

Is the environment offline or is it judged from the code or from the global configuration? Which method do you think is better? 
/cc @zryfish

**Comment by zryfish** [comment]
Why we need this code? IMO, dockerhub api can be called directly from console, we don't have to implement api again.

**Comment by soulseen** [comment]
same effect with call dockerhub api directly from console, but can not generate api documentation.

**Comment by runzexia** [comment]
I think this PR can be closed because the front end will use dockerhub api.

/close

**Pull request closed without merging**
