### PR TITLE
Uniform code format

### PR DESCRIPTION
**Pull request by sologgfun**
### What type of PR is this?
/kind cleanup

### What this PR does / why we need it:

Unified the event handler syntax for CRD-controllers with inconsistent syntax to the shorthand syntax

### CODE REVIEW

**Comment by wansir** [comment]
/ok-to-test

@sologgfun Thanks for your contribution!

**Comment by sologgfun** [comment]
> /ok-to-test
> 
> @sologgfun Thanks for your contribution!

This is just a small task; I hope to make more contributions to kubeSphere in the future.

**Pull request merged**
