### PR TITLE
apiserver: remove redundant GroupVersionResource

### PR DESCRIPTION
**Pull request by opsnull**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wansir** [comment]
@opsnull Thanks for your contribution! Pls signed-off your commits and push again.

**Comment by opsnull** [comment]
@wansir  signed-ff done.

**Comment by yuswift** [comment]
@opsnull 
#3967 has fixed the `goimport` error. Please rebase to pass ci.

**Comment by yuswift** [comment]
@wansir pls approve the GitHub workflow to run

**Pull request merged**
