### PR TITLE
change controller-gen crds source path

### PR DESCRIPTION
**Pull request by RolandMa1986**
Signed-off-by: Roland.Ma <rolandma@yunify.com>
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
1. CRD can't be generated by run the `make manifest` command when verifying #3912 in the master branch.
2. Generate specific CRDs by folder.
3. Clean out unnecessary CRDs. 

**Root Cause:**
Since we moved APIs definitions from the `pkg/apis` package to the `kubesphere.io/api` module, `make manifest` no longer works with old path "paths=./pkg/apis/...".
Correct the path with "paths=kubesphere.io/api/...".

**Which issue(s) this PR fixes**:

Fixes ##3912
Related #3830

### CODE REVIEW

**Comment by yuswift** [comment]
duplicate #3848 
we need to exclude service mesh dir to avoid generating crd files.

**Comment by RolandMa1986** [comment]
Ok, seems there are still some issues need to be fixed. To resolve the case above, we need to exclude the service mesh CRDs.
CRDs generate strategy needs to be changed. Before that, I'd like to discuss which CRD should be put into the "config/crds" folder?

Currently, most of the CRDs that be used by KubeSphere were put into the "config/crds"  folder, for example:
1. Third-party components crds like `istio-crds.yaml`, `snapshot.storage.k8s.io_volumesnapshot.yaml`.  They were copied into the folder when related to feature check-in.
2. Third-party go API references and generated by `make manifest`, like `crd.projectcalico.org_blockaffinities.yaml`. Also include Auditing, monitoring, and Notification.
3. Federated resources, the type defined in the API package. 
4. Other API packages defined by KubeSphere.

Oboiversly case 1 and case 2 are not necessary. Those crds are managed by their own Helm chart or YAML when installing those components. For case 3, those federated crds were actually not be used, because we typically use the "kubefedctl" command to generate them instead of "make manifest".   I think that CRDs in cases 1 to 3 be should be removed from the folder. Firstly, we don't use them at all, compare with the ks-installer, ks-core only maintains CRDs defined by KS. Secondly, those CRD would be out of date when those components update to another version.

The "config/crds" folder should only contain CRDs that be defined and used by KubeSphere controllers. **So I propose to generated CRDs for each specific folder instead of all folders under "./apis/...".** 

Special cases like Service Mesh should be excluded, developers should maintain the CRD by themself.

/cc @zackzhangkai @yuswift @zryfish

**Comment by yuswift** [comment]
Agree with you. But for snapshot, maybe we need to keep the crd files cause if we remove them, the controller manager will output some error logs.

**Comment by yuswift** [comment]
Please make sure the files removed exist in their own helm charts.

**Comment by RolandMa1986** [comment]
> Agree with you. But for snapshot, maybe we need to keep the crd files cause if we remove them, the controller manager will output some error logs.

I don't think it's necessary. We can warn users that the snapshot was not installed on the cluster, or the CSI doesn't support the snapshot.

**Comment by yuswift** [comment]
> > Agree with you. But for snapshot, maybe we need to keep the crd files cause if we remove them, the controller manager will output some error logs.
> 
> I don't think it's necessary. We can warn users that the snapshot was not installed on the cluster, or the CSI doesn't support the snapshot.

Is snapshot crd necessary for ks-controller-manager? If not, I think we can remove it from ks-core. BTW, how do we install snapshot crd after we have installed ks-core with helm? @RolandMa1986

**Comment by stoneshi-yunify** [comment]
> > > Agree with you. But for snapshot, maybe we need to keep the crd files cause if we remove them, the controller manager will output some error logs.
> > 
> > 
> > I don't think it's necessary. We can warn users that the snapshot was not installed on the cluster, or the CSI doesn't support the snapshot.
> 
> @stoneshi-yunify Is snapshot crd necessary for ks-controller-manager? If not, I think we can remove it from ks-core. BTW, how do we install snapshot crd after we have installed ks-core with helm? @RolandMa1986

No, snapshot crd is just a crd like any other crds. It's absolute unnecessary for ks-core. User can install the crd the snapshot-controller anytime. Just need to ensure ks won't crash without them.

**Comment by RolandMa1986** [comment]
> Please make sure the files removed exist in their own helm charts.
All the CRDs that had been deleted can be found in the following folders.
https://github.com/kubesphere/ks-installer/tree/master/roles/common/files/snapshot-controller
https://github.com/kubesphere/ks-installer/tree/master/roles/ks-monitor/files/monitoring-dashboard
https://github.com/kubesphere/ks-installer/tree/master/roles/ks-monitor/files/notification-manager
https://github.com/kubesphere/ks-installer/tree/master/roles/ks-auditing/files/kube-auditing
https://github.com/kubesphere/ks-installer/tree/master/roles/ks-istio/files/istio
https://github.com/kubesphere/ks-installer/tree/master/roles/ks-multicluster/files/kubefed/federatedcrds

**Comment by wansir** [comment]
I think you should split the unit test change to another PR, and squash commits.  CRD generation rules can be supplemented by others.

**Comment by RolandMa1986** [comment]
> I think you should split the unit test change to another PR, and squash commits. CRD generation rules can be supplemented by others.

Those 3 UT test would be failed, when removed the Dashboard and Notification's CRDs.

**Pull request merged**
