### PR TITLE
lazy init events client and optimize events search

### PR DESCRIPTION
**Pull request by junotx**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:

Lazily init events client  (like #2287)
Optimize events search perfomance (like #2423)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@huanggze pls take a look at @junotx 's PR. Basically it looks similar but not exactly the same with yours.
It's ok for now because we're going to refine these similar logic for logging, auditing and events in the future.

**Comment by huanggze** [comment]
I think junotx's PR looks good. We definitely need refactor logging, auditing and events in the next release.

/lgtm

**Pull request merged**
