### PR TITLE
fix import error

### PR DESCRIPTION
**Pull request by zackzhangkai**
Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>

**What type of PR is this?**

Fix errors as below:

```bash
➜  kubesphere git:(master) ✗ go mod vendor
kubesphere.io/kubesphere/pkg imports
        k8s.io/kube-openapi/cmd/openapi-gen/: malformed import path "k8s.io/kube-openapi/cmd/openapi-gen/": trailing slash
```

### CODE REVIEW

**Comment by yuswift** [comment]
Tried to run `hack/update-vendor.sh` but got the following error:
```
go mod tidy
go: downloading kubesphere.io/monitoring-dashboard v0.1.2
go: downloading github.com/docker/engine v1.4.2-0.20200203170920-46ec8731fbce
go: downloading github.com/go-resty/resty/v2 v2.5.0
verifying github.com/go-resty/resty/v2@v2.5.0: checksum mismatch
	downloaded: h1:GmCjQ7qW3Dzr3Lh7FvTrRJSWgYNWswDdOy+T8sgTAFI=
	go.sum:     h1:WFb5bD49/85PO7WgAjZ+/TJQ+Ty1XOcWEfD1zIFCM1c=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.```
I think we need to fix this error firstly, then run `hack/update-vendor.sh` to update the dependencies.

**Comment by wansir** [comment]
> Tried to run `hack/update-vendor.sh` but got the following error:
> 
> ```
> go mod tidy
> go: downloading kubesphere.io/monitoring-dashboard v0.1.2
> go: downloading github.com/docker/engine v1.4.2-0.20200203170920-46ec8731fbce
> go: downloading github.com/go-resty/resty/v2 v2.5.0
> verifying github.com/go-resty/resty/v2@v2.5.0: checksum mismatch
> 	downloaded: h1:GmCjQ7qW3Dzr3Lh7FvTrRJSWgYNWswDdOy+T8sgTAFI=
> 	go.sum:     h1:WFb5bD49/85PO7WgAjZ+/TJQ+Ty1XOcWEfD1zIFCM1c=
> 
> SECURITY ERROR
> This download does NOT match an earlier download recorded in go.sum.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'.
> ```
> 
> I think we need to fix this error firstly, then run `hack/update-vendor.sh` to update the dependencies.

https://github.com/go-resty/resty/issues/415#issuecomment-797431805

**Pull request merged**
