### PR TITLE
fix groupbinding controller unittest

### PR DESCRIPTION
**Pull request by wansir**
### What type of PR is this?

/kind failing-test

### What this PR does / why we need it:

Fix unexpected unit test failure.

### Which issue(s) this PR fixes:

Fix the failed unit test, https://prow.kubesphere.io/view/s3/prow-logs/pr-logs/pull/kubesphere_kubesphere/4455/pull-kubesphere-unit-test/1463412604385890304.

### Special notes for reviewers:

Filter out all read action before comparing.

### Does this PR introduced a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by RolandMa1986** [comment]
@wansir Is there a potential race condition issue？

**Comment by wansir** [comment]
> @wansir Is there a potential race condition issue？

Do you mean that unit tests are parallel? We create `fixture` for each test.

**Comment by RolandMa1986** [comment]
> > @wansir Is there a potential race condition issue？
> 
> Do you mean that unit tests are parallel? We create `fixture` for each test.

Ok, I think it is because the Informers was started in another goroutine. So the Watch Action will be added to the k8s actions asynchronously. So we should filter all the watch actions.

/lgtm

**Pull request merged**
