### PR TITLE
kubesphere-fix-GetDeployRevision

### PR DESCRIPTION
**Pull request by zehuaiWANG**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug

**What this PR does / why we need it**:
不属于deployment的rs也可能label相同，我觉得通过label选择器来挑选是不完全对的，最好的方法是使用`metaV1.IsControlledBy(rs, deploy)`来校验。

### CODE REVIEW

**Comment by wansir** [comment]
This API will be deprecated, revision id is too difficult to understand.

**Comment by zehuaiWANG** [comment]
@wansir More than one interface has been modified in this PR, which is not only because revision id is too difficult to understand a hard problem, but also it's a bug which will case error.

**Comment by wansir** [comment]
Use `metav1.IsControlledBy` to determine that the relationship is correct,  we will refactor this API instead of fixing it.

**Comment by zehuaiWANG** [comment]
@wansir okay, I agree, please close this pr if it's unnecessary

**Comment by zryfish** [comment]
closing per previous comments

**Pull request closed without merging**
