### PR TITLE
Fix the ks-apiserver panic due to the devopsprojects CRD missing

### PR DESCRIPTION
**Pull request by LinuxSuRen**
### What type of PR is this?

/kind bug
/area devops

### What this PR does / why we need it:
APIServer will panic if the DevOps component was not enbaled.

### Which issue(s) this PR fixes:

None.

### Special notes for reviewers:
Do not get the devopsprojects if the DevOps was not enabled.

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
I'm trying to reproduce this issue.

**Comment by JohnNiang** [comment]
hi @LinuxSuRen , I would appreciate it if you could provide a test docker image.

**Comment by LinuxSuRen** [comment]
> hi @LinuxSuRen , I would appreciate it if you could provide a test docker image.

Of course, see it below:

`surenpi/ks-apiserver:fix-apiserver-panic`

**Pull request merged**
