### PR TITLE
Support snapshotclass management 

### LINKED ISSUE #4281: Support volumesnapshotclass management in ks-console
# Background
Currently ks-console doesn't support volumesnapshotclass management (crud) in ks-console.

# Proposal
volumesnapshotclass is similar to storageclass, but much simpler.  We should support the management of it in ks-console, in order to to ease user's manual effort.

/area console
/area storage
/kind feature-request

### PR DESCRIPTION
**Pull request by f10atin9**
Signed-off-by: f10atin9 <f10atin9@kubesphere.io>

### What type of PR is this?

/kind feature

### What this PR does / why we need it:
In order to support the management of snapshotclass in ks-console, this part of the back-end code is added.
### Which issue(s) this PR fixes:

Fixes #4281 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by zryfish** [comment]
@f10atin9  What's next? Do we need to change console adding snapshotclass? How do we use these API?

**Comment by f10atin9** [comment]
> @f10atin9 What's next? Do we need to change console adding snapshotclass? How do we use these API?

Next, snapshotcontent will be added. After that ks-console will update the snapshotclass and snapshotcontent pages.

**Review by stoneshi-yunify — APPROVED** [review]
/lgtm

**Pull request merged**
