### PR TITLE
Support make help

### LINKED ISSUE #4143: [Feature] Better Makefile
Support `make help`

**What's it about?**
  

Can use command of `make help` to check what have in Makefile.  

Simple example:  

```shell
lanrendeMacBook-Pro:kubesphere lanren$ make help
all               Test and build all of binary
binary            Build all of binary
ks-apiserver      Build ks-apiserver
ks-controller-manager Build ks-controller-manager
verify-all        Run all verify scripts hack/verify-*.sh
e2e               Build e2e binary
fmt               Run go fmt against code 
goimports         Format all import, `goimports` is required.
vet               Run go vet against code
manifests         Generate manifests e.g. CRD, RBAC etc.
deploy            deploy
mockgen           mockgen
deepcopy          deepcopy
openapi           openapi
container         Build the docker image
container-push    Build and push
container-cross   Build container images for multiple platforms. Currently, only linux/amd64,linux/arm64 are supported.
container-cross-push Build and push
helm-package      helm-package
helm-deploy       helm-deploy
helm-uninstall    helm-uninstall
test              Run tests
clean             clean
clientset         find or download controller-gen,download controller-gen if necessary
```  

Now

**What's the reason why we need it?**
  

We don't need open Makefile for found some make command anymore. Free your eyes!  More important, people who are new to the project can better understand and use Makefile.  

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up. 👍 

**Area Suggestion**

/kind feature-request

### PR DESCRIPTION
**Pull request by liangyuanpeng**
### What type of PR is this?
/kind feature

### What this PR does / why we need it:    

1. Support compile all of component to binary, use command `make binary`  
2. Support `make help`

issue content: ↓↓↓↓

We don't need open Makefile for found some make command anymore. Free your eyes! More important, people who are new to the project can better understand and use Makefile.

```shell
lanrendeMacBook-Pro:kubesphere lanren$ make help
all               Test and build all of binary
binary            Build all of binary
ks-apiserver      Build ks-apiserver
ks-controller-manager Build ks-controller-manager
verify-all        Run all verify scripts hack/verify-*.sh
e2e               Build e2e binary
fmt               Run go fmt against code 
goimports         Format all import, `goimports` is required.
vet               Run go vet against code
manifests         Generate manifests e.g. CRD, RBAC etc.
deploy            deploy
mockgen           mockgen
deepcopy          deepcopy
openapi           openapi
container         Build the docker image
container-push    Build and push
container-cross   Build container images for multiple platforms. Currently, only linux/amd64,linux/arm64 are supported.
container-cross-push Build and push
helm-package      helm-package
helm-deploy       helm-deploy
helm-uninstall    helm-uninstall
test              Run tests
clean             clean
clientset         find or download controller-gen,download controller-gen if necessary
```  

### Which issue(s) this PR fixes:

Fixes #4143 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
NONE
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zryfish** [comment]
@liangyuanpeng  Thanks for your contribution. This would be a very useful feature for our new contributors. I like it.  Please fill up release-note section in the PR description, since there is no user-facing change introduced by this PR, you can just put `NONE`.

**Review by JohnNiang — CHANGES_REQUESTED** [review]
Please be aware of `begin to do sth.` instead of `begin do sth.`.

**Pull request merged**
