### PR TITLE
add interface for iam

### PR DESCRIPTION
**Pull request by shaowenchen**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

add sync interface for Iam， including:

```bash
AddGlobalRole(roleName string, ids GlobalPermissionIds, overwrite bool) error
GetGlobalRole(roleName string) (string, error)

AddProjectRole(roleName string, pattern string, ids ProjectPermissionIds, overwrite bool) error
DeleteProjectRoles(roleName ...string) error

AssignProjectRole(roleName string, sid string) error
UnAssignProjectRole(roleName string, sid string) error

AssignGlobalRole(roleName string, sid string) error
UnAssignGlobalRole(roleName string, sid string) error

DeleteUserInProject(sid string) error
```

usage:

```bash
err = c.devopsClient.AssignGlobalRole(modeldevops.JenkinsAdminRoleName, username)
```

### CODE REVIEW

**Comment by shaowenchen** [comment]
@zryfish

**Comment by zryfish** [comment]
Please add more commnets for interface methods, this is a good opportunity to exercise your documentation skill

**Comment by wansir** [comment]
fix: https://github.com/kubesphere/kubesphere/issues/2284

**Comment by shaowenchen** [comment]
> Please add more commnets for interface methods, this is a good opportunity to exercise your documentation skill

I had added some comments.

**Pull request merged**
