### PR TITLE
kubesphere-add-default-param

### PR DESCRIPTION
**Pull request by zehuaiWANG**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind cleanup

**What this PR does / why we need it**:
获取请求参数的地方，可以封装方法来处理默认值的问题，其他地方也可以对应修改。

### CODE REVIEW

**Comment by wansir** [comment]
`reverse` parameter can also be obtained through GetBoolValueWithDefault

**Comment by zehuaiWANG** [comment]
@wansir Yes, I'm just give an example. It should be handled like this. There are many code such like this  in the project, but I'm not familiar with this part of the code, so I don't know their specific places.

**Comment by wansir** [comment]
You can commit the code, let me complete it.

**Comment by zehuaiWANG** [comment]
@wansir Yes, you can merge this part of the code and then continue to modify it

**Pull request merged**
