### PR TITLE
fix tcp match error

### PR DESCRIPTION
**Pull request by StevenBrown008**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:
The tcp match  has several kind, such as port, sourceLabels, gateway, destinationSubnets . We should not just put one port match element in the L4MatchAttributes match array, this may overwrite the original match element, and  cause an error.
So I modify the code ,like the above http match code , just insert the port match in every match element to fix this problem.
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

None

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by iawia002** [comment]
The code itself LGTM, this part of the code was last modified in the PR #4560, I don't know why they didn't handle the TCP rules this way in the first place, and I'm not sure if they did it on purpose, this needs to be double-checked by the person responsible for the module.

**Comment by StevenBrown008** [comment]
please /cc @zackzhangkai @zryfish , thanks !

**Pull request merged**
