### PR TITLE
fix: revert packages from vendor/kubesphere.io

### PR DESCRIPTION
**Pull request by zhu733756**
Signed-off-by: zhu733756 <talonzhu@yunify.com>

### What type of PR is this?

/kind cleanup

### What this PR does / why we need it:

Unnecessary packages were introduced via the 'go mod vendor' command with pr  #4194, this pr aims to fix it.

### Which issue(s) this PR fixes:

Fixes #4194

### Special notes for reviewers:
```
None
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by benjaminhuo** [comment]
The release notes are wrong, the release notes should be None instead of `clean up the folders`

**Comment by zhu733756** [comment]
> The release notes are wrong, the release notes should be None instead of `clean up the folders`

fixed

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
