### PR TITLE
feat: add casdoor as an OAuth 2.0 Identity Provider

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
### What type of PR is this?
/kind feature

### What this PR does / why we need it:
feat: add casdoor as an OAuth 2.0 Identity Provider following the  instructions in <https://kubesphere.io/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider/>
### Which issue(s) this PR fixes:
None

### Special notes for reviewers:

None
### Does this PR introduced a user-facing change?
No

### CODE REVIEW

**Comment by sagilio** [comment]
The [path](https://github.com/kubesphere/kubesphere/blob/master/vendor/kubesphere.io/api) just is a link, so we need not update it.  Here is the [doc](https://github.com/kubesphere/kubesphere/blob/master/staging/README.md).

**Comment by RolandMa1986** [comment]
Hi @ComradeProgrammer,
It looks like casdoor suppors OIDC.  Is that possible to use OIDC directly?

**Comment by wansir** [comment]
It is recommended to use Gomega With Ginkgo as the testing framework. Using `./hack/update-vendor.sh` to update the vendor directory.

**Comment by ComradeProgrammer** [comment]
> Hi @ComradeProgrammer, It looks like casdoor suppors OIDC. Is that possible to use OIDC directly?

Hi. I am aware of that kubesphere supports OIDC, but somehow after server tries it turned out that the oidc configuration didn't work. I followed the instructon in this doc <https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/oidc-identity-provider/> and add configurations, but nothing happened on kubesphere. I didn't see any entrance of logging in with an oidc account. I also tried google oidc , which is the same as the doc, but nothing happened either So I decided to use the oauth2,0 provider.

**Comment by ComradeProgrammer** [comment]
> @ComradeProgrammer It is recommended to use Gomega With Ginkgo as the testing framework. Using `./hack/update-vendor.sh` to update the vendor directory.

roger that, proper changes have been made

**Comment by ComradeProgrammer** [comment]
> @ComradeProgrammer It is recommended to use Gomega With Ginkgo as the testing framework. Using `./hack/update-vendor.sh` to update the vendor directory.

Well I think this time the unnecessary files in vendor have been removed

**Comment by RolandMa1986** [comment]
> > Hi @ComradeProgrammer, It looks like casdoor suppors OIDC. Is that possible to use OIDC directly?
> 
> Hi. I am aware of that kubesphere supports OIDC, but somehow after serveral tries it turned out that the oidc configuration didn't work. I followed the instructons in this doc https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/oidc-identity-provider/ and added configurations, but nothing happened on kubesphere. I didn't see any entrance of logging in with an oidc account. I also tried google oidc , which is the same as the doc, but nothing happened either. So I decided to use the oauth2,0 provider. Sorry for the long delay

Google OIDC and Okta had been tested before.  Please double-check the OIDC settings. And we also plan to publish a blog about [how to integrate Okta](https://hackmd.io/@WRhJ0dcsRn66-rlDnlhBLQ/By7v4fGOt).

**Pull request closed without merging**
