### PR TITLE
fix: spell mistake: hostClusterNmae -> hostClusterName

### PR DESCRIPTION
**Pull request by songf0011**
### What type of PR is this?

/kind cleanup

### What this PR does / why we need it:
fix spell mistake: hostClusterNmae -> hostClusterName

### Which issue(s) this PR fixes:

Fixes #
#4568
### Special notes for reviewers:
```
None
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by iawia002** [comment]
Nice catch!

/lgtm

**Review by LinuxSuRen — COMMENTED** [review]
LGTM

**Pull request merged**
