### PR TITLE
Add proxy devops APIs request to ks-devops

### PR DESCRIPTION
**Pull request by LinuxSuRen**
### What type of PR is this?

/kind cleanup

### What this PR does / why we need it:

Technically speaking, the DevOps feature could be an independent application. That means it only needs to rely on Kubernetes instead of KubeSphere. With the following plan, users can install DevOps on any kind of Kubernetes.

Get more details from https://github.com/kubesphere/ks-devops/issues/107

### Which issue(s) this PR fixes:

Fixes https://github.com/kubesphere/ks-devops/issues/107

### Special notes for reviewers:

Considering there're too many files changed in this PR, please read the following suggestion.

Mostly, I delete the DevOps-related code lines. And move it to [a new project](https://github.com/kubesphere/ks-devops). About this part, you don't need to take too much time to review.

I bring the generic proxy for APIs of DevOps. See also

https://github.com/kubesphere/kubesphere/pull/4129/files#diff-94b52d23cc5a8496b5fca6db44a210542685b16dd10890f19b3f74b8c6631cccR34

hi @JohnNiang , we don't need the project [ks-devops-plugin](https://github.com/kubesphere-sigs/ks-devops-plugin) for now. Please don't forget to remove it from https://github.com/kubesphere/ks-installer/pull/1622

Please use the image `surenpi/ks-apiserver:devops-proxy` if there's anyone willing to help to test it.

### Does this PR introduced a user-facing change?

```release-note
Move the codebase of DevOps into a separate project
```

### Additional documentation, usage docs, etc.:

```docs
None.
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
Thanks for reminding. I've appended a TODO into https://github.com/kubesphere/ks-installer/pull/1622.

**Comment by zryfish** [comment]
Big change, but I think we need it. @liuyp2018 @wenxin-01 I am concerned we may introduce regression issues here, so maybe we can test this as soon as possible.

**Comment by LinuxSuRen** [comment]
> m concerned we may introduce regression issues here, so maybe we can test this as soon as possib

Of course, we need a lot of tests.

**Comment by LinuxSuRen** [comment]
hi @wansir , hopefully, this PR can get your review.

**Comment by JohnNiang** [comment]
https://github.com/kubesphere/kubesphere/blob/418a2a09c7f751cc6f1bcacbf141c6f64e6aa256/pkg/kapis/generic/generic.go#L102-L111

@zryfish , i'm confused that line `#106` makes url replaced the group name with empty string by default, can you let me know why we need it?

**Comment by zryfish** [comment]
> https://github.com/kubesphere/kubesphere/blob/418a2a09c7f751cc6f1bcacbf141c6f64e6aa256/pkg/kapis/generic/generic.go#L102-L111
> 
> @zryfish , i'm confused that line `#106` makes url replaced the group name with empty string by default, can you let me know why we need it?

API group name is required to construct KubeSphere APIs, for example `GET /kapis/devops.kubesphere.io/v1alpha1/namespaces/foo/devops/bar`, means to get `devops` named `bar` in namespace `foo` which under API group `devops.kubesphere.io/v1alpha1`. The proxied backend services do not necessarily have the API group. The proxied service API pattern may look like `example.com/api/v1/devops/bar`. When proxied request `GET /kapis/devops.kubesphere.io/v1alpha1/namespaces/foo/devops/bar` to backend service, the `/kapis/apigroup` is striped and prepend the endpoint path.

**Comment by JohnNiang** [comment]
@zryfish Thanks for your concise and comprehensive explanation. That make sense to me.

**Comment by LinuxSuRen** [comment]
Any updates?

**Pull request merged**
