### PR TITLE
Fix client typo

### PR DESCRIPTION
**Pull request by JohnNiang**
Signed-off-by: johnniang <johnniang@fastmail.com>

Fix client typo.

/kind flake

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
/remove-lgtm
/hold
Please fix the ci errors.

**Comment by JohnNiang** [comment]
I think the failing check is unrelated my changes, . Can you re-run the failing check? @LinuxSuRen 

image

**Comment by LinuxSuRen** [comment]
> I think the failing check is unrelated my changes,

It's true. But it might be a potential issue, you can contact the person who makes changes with the related unit test code lines last time.

It's pretty easy to re-run the CI build. You just need to close and reopen this PR.

**Comment by JohnNiang** [comment]
Please have a look at failing check <https://github.com/kubesphere/kubesphere/pull/3868/checks?check_run_id=2556839293> related [notification_controller_test](https://github.com/kubesphere/kubesphere/blob/master/pkg/controller/notification/notification_controller_test.go) @wanjunlei .

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
