### PR TITLE
feature: support setting host cluster name

### PR DESCRIPTION
**Pull request by yuswift**
Signed-off-by: yuswift <yuswift2018@gmail.com>

### What type of PR is this?
/kind feature
### What this PR does / why we need it:
We can set the host cluster name in the `kubesphere.yaml` now, e.g:
```
authentication:
  authenticateRateLimiterMaxTries: 10
  authenticateRateLimiterDuration: 10m0s
  loginHistoryRetentionPeriod: 168h
  maximumClockSkew: 10s
  multipleLogin: True
  kubectlImage: kubesphere/kubectl:v1.19.1
  jwtSecret: "qTcNlzhUlTa6bjo4lZaXG1Xr"
network:
  ippoolType: none
multicluster:
  enable: true
  agentImage: kubesphere/tower:v0.2.0
  proxyPublishService: tower.kubesphere-system.svc
  hostClusterName: control
```
### Which issue(s) this PR fixes:

part of #4158 
### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
the cluster controller now supports setting the host cluster name, default set to host
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zryfish** [comment]
What if the user wants to change the name of the existing host cluster?

**Comment by yuswift** [comment]
> What if the user wants to change the name of the existing host cluster?

The name of the cluster can not be changed after being created. I think there is a workaround for the users `stop the cluster controller, delete the host cluster, update the kubesphere.yaml, restart the controller`

**Comment by yuswift** [comment]
> > What if the user wants to change the name of the existing host cluster?
> 
> The name of the cluster can not be changed after being created. I think there is a workaround for the users `stop the cluster controller, delete the host cluster, update the kubesphere.yaml, restart the controller`

But the solution is a very bad idea. The users shouldn't change the cluster name, because it will affect the federation resources which are managed by kubfed.

**Pull request merged**
